### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by elrhomariyounes** [supabase/supabase-csharp#1]
# Hello, I would like to contribute

* Is there any requirements to setup the project locally ?
* Any required steps before building the Repo ?

Thank you.

**Comment by acupofjose** [comment]
@elrhomariyounes  no requirements other than the nuget packages defined in the project, but visual studio will handle those for you.

That and docker if you want to do local development!

**Comment by elrhomariyounes** [comment]
Superb, I will give it a try and start looking in to it. Make some samples or if there is any known issues.

**Comment by elrhomariyounes** [comment]
Hello @acupofjose, I'm very motivated to give a try the realtime client. There is a separate repo (realtime-csharp) ? Thank you.

**Comment by acupofjose** [comment]
@elrhomariyounes there has been one kindly provided by @kiwicopple - I'll get it initialized and send you a message when it's ready for contributions!

**Comment by acupofjose** [comment]
@elrhomariyounes please see https://github.com/supabase/realtime-csharp as the repo to contribute to! It is mostly stubbed at the moment, but should be more than enough to work with!
