### ISSUE TITLE
Xamarin.Forms todo app example

### ISSUE THREAD

**Issue by elrhomariyounes** [supabase/supabase-csharp#2]
Hello @acupofjose, I made a todo app and I was wondering if we should trigger a pre-release for supabase-csharp to use the whole library and add it to the [Supabase repo](https://github.com/supabase/supabase) examples.

I only used postgrest-csharp and realtime-csharp in the example. If you have some time could you check it out and let me know what do you think [here](https://github.com/elrhomariyounes/supabase-xamarin-forms-example)

**Comment by acupofjose** [comment]
@elrhomariyounes this is great! Thanks so much for working on this repo. I just pushed the prerelease package - you'll find it here: https://www.nuget.org/packages/supabase-csharp (once the analysis that nuget does completes).

I think it'd be great to have it in the examples. Preferably with some interactions with `Auth` if possible. The example in this repo (though very incomplete) does provide a way for you to store Auth Sessions.

**Comment by elrhomariyounes** [comment]
Thank you @acupofjose. I will try to add some Authentication and Authorization to the example.
