### ISSUE TITLE
Is it possible to pass in our own authorisation bearer token

### ISSUE THREAD

**Issue by jeylanicode** [supabase/supabase-csharp#5]
https://github.com/supabase/supabase-csharp/blob/98ef31fa35aebcec97c8847737f3ff552e56ef68/Supabase/Client.cs#L142

I want to be able to pass my token like so:

<img width="913" alt="Screenshot 2021-06-01 at 21 17 05" src="https://user-images.githubusercontent.com/83839350/120384992-c7981480-c31e-11eb-8bdd-66f74ba6f8bb.png">

But it is being overwritten by the fact that it checks only if there is a current session which I can't create without using the sign in method.

**Comment by acupofjose** [comment]
So you're getting an `access_token` without using the Supabase.Auth calls?

**Comment by acupofjose** [comment]
Available in `v0.1.6-prerelease` you should see it hit NuGet in the next 15-20 minutes or so!

**Comment by jeylanicode** [comment]
You are a LEGEND! Thank you!
